version: "4"
services:
  app-mongodb:
    image: mongo:4.2
    container_name: "app-mongodb"
    ports:
      - 27017:27017
  springboot-mongodb:
    image: springboot-mongodb:1.0
    container_name: springboot-mongodb
    ports:
      - 8080:8080
    links:
      - app-mongodb